// This program takes the power of different numbers and is compiled
// using CMake
// By: Nick from CoffeeBeforeArch

#include <iostream>
#include <cmath>

// Add header generated by CMake
#include "PowersConfig.h"

// Conditionally add our myPow function
#ifdef USE_MYMATH
#include "exponent.h"
#endif

using namespace std;

int main(){
    // Print the version numbers that we generate
    cout << "Major Version: " << Powers_VERSION_MAJOR << endl;
    cout << "Minor Version: " << Powers_VERSION_MINOR << endl;

    // Compute some a power calculation
    int base = 4;
    int exponent = 3;

// Conditionally use our myPow function
#ifdef USE_MYMATH
    int result = myPow(base, exponent);
#else
    int result = pow(base, exponent);
#endif

    // Print the result
    cout << base << "^" << exponent << " = " << result << endl;
    return 0;
}
